# Generated by Django 5.2.7 on 2025-10-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coin", models.CharField(max_length=64)),
                ("quantity", models.FloatField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
